server:
  port: 9000

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka9000.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "https://${eureka.instance.hostname}:${server.port}/eureka/"
